import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  transpilePackages: [
    "@rabbit-and-pig/shared",
    // react-markdown v10 and all its ESM-only dependencies
    "react-markdown",
    "unified",
    "remark-parse",
    "remark-rehype",
    "hast-util-to-jsx-runtime",
    "hast-util-whitespace",
    "html-url-attributes",
    "mdast-util-from-markdown",
    "mdast-util-mdx-expression",
    "mdast-util-mdx-jsx",
    "mdast-util-mdxjs-esm",
    "mdast-util-phrasing",
    "mdast-util-to-hast",
    "mdast-util-to-markdown",
    "mdast-util-to-string",
    "micromark",
    "micromark-core-commonmark",
    "micromark-factory-destination",
    "micromark-factory-label",
    "micromark-factory-space",
    "micromark-factory-title",
    "micromark-factory-whitespace",
    "micromark-util-character",
    "micromark-util-chunked",
    "micromark-util-classify-character",
    "micromark-util-combine-extensions",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "micromark-util-symbol",
    "micromark-util-types",
    "unist-util-is",
    "unist-util-position",
    "unist-util-stringify-position",
    "unist-util-visit",
    "unist-util-visit-parents",
    "vfile",
    "vfile-message",
    "bail",
    "ccount",
    "character-entities",
    "character-entities-html4",
    "character-entities-legacy",
    "character-reference-invalid",
    "comma-separated-tokens",
    "decode-named-character-reference",
    "devlop",
    "estree-util-is-identifier-name",
    "is-alphabetical",
    "is-alphanumerical",
    "is-decimal",
    "is-hexadecimal",
    "is-plain-obj",
    "longest-streak",
    "parse-entities",
    "property-information",
    "space-separated-tokens",
    "stringify-entities",
    "trim-lines",
    "trough",
    "zwitch",
    "@ungap/structured-clone",
  ],
};

export default nextConfig;

